# Generated by Django 5.0.6 on 2024-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='relative/path/to/upload'),
        ),
    ]
