# Generated by Django 5.0.6 on 2024-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_alter_tour_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='relative/path/to/upload'),
        ),
        migrations.AlterField(
            model_name='hospedajeacomodacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='relative/path/to/upload'),
        ),
    ]
