# Generated by Django 5.0.6 on 2024-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_paquetetour_id_hospedaje_acomodacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
