# Generated by Django 5.0.6 on 2024-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_alter_tour_duracion_alter_tour_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='telefono',
            field=models.CharField(default=29303938, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acomodacion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adicion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
        migrations.AlterField(
            model_name='hospedajeacomodacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
