# Generated by Django 5.1 on 2024-09-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_hospedaje_telefono_alter_acomodacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
        migrations.AlterField(
            model_name='acomodacion',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='adicion',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='destino',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='incluye',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='no_incluye',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
