# Generated by Django 5.0.7 on 2024-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
