# Generated by Django 5.0.7 on 2024-08-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_alter_tour_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='telefono',
            field=models.CharField(default=312345689, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquetetour',
            name='id_hospedaje_acomodacion',
            field=models.ForeignKey(db_column='id_hospedaje_acomodacion', default=1, on_delete=django.db.models.deletion.PROTECT, to='viajes.hospedajeacomodacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adicion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_destino',
            field=models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.PROTECT, to='viajes.destino'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='id_acomodacion',
            field=models.ForeignKey(blank=True, db_column='id_acomodacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='viajes.acomodacion'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='id_adicion',
            field=models.ForeignKey(blank=True, db_column='id_adicion', null=True, on_delete=django.db.models.deletion.PROTECT, to='viajes.adicion'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='id_paquete_tour',
            field=models.ForeignKey(blank=True, db_column='id_paquete_tour', null=True, on_delete=django.db.models.deletion.PROTECT, to='viajes.paquetetour'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='id_reserva',
            field=models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.PROTECT, to='viajes.reserva'),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='id_destino',
            field=models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.PROTECT, to='viajes.destino'),
        ),
        migrations.AlterField(
            model_name='hospedaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
        migrations.AlterField(
            model_name='hospedajeacomodacion',
            name='id_acomodacion',
            field=models.ForeignKey(db_column='id_acomodacion', on_delete=django.db.models.deletion.PROTECT, to='viajes.acomodacion'),
        ),
        migrations.AlterField(
            model_name='hospedajeacomodacion',
            name='id_hospedaje',
            field=models.ForeignKey(db_column='id_hospedaje', on_delete=django.db.models.deletion.PROTECT, to='viajes.hospedaje'),
        ),
        migrations.AlterField(
            model_name='hospedajeacomodacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paquetetour',
            name='id_paquete',
            field=models.ForeignKey(db_column='id_paquete', on_delete=django.db.models.deletion.PROTECT, to='viajes.paquete'),
        ),
        migrations.AlterField(
            model_name='paquetetour',
            name='id_tour',
            field=models.ForeignKey(db_column='id_tour', on_delete=django.db.models.deletion.PROTECT, to='viajes.tour'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='viajes.cliente'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id_destino',
            field=models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.PROTECT, to='viajes.destino'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
