# Generated by Django 5.0.7 on 2024-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_hospedaje_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedajeacomodacion',
            name='fecha_fin',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospedajeacomodacion',
            name='fecha_inicio',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
