# Generated by Django 5.0.7 on 2024-10-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_hospedajeacomodacion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomodacion',
            name='capacidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
