# Generated by Django 5.0.6 on 2024-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodacion',
            fields=[
                ('id_acomodacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('estado_acomoda', models.IntegerField()),
            ],
            options={
                'db_table': 'acomodacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adicion',
            fields=[
                ('id_adicion', models.AutoField(db_column='id_Adicion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('costo', models.FloatField(db_column='Costo')),
                ('estado', models.IntegerField(db_column='Estado')),
            ],
            options={
                'db_table': 'adicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=200)),
                ('tipo_doc', models.CharField(db_column='Tipo_doc', max_length=20)),
                ('telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('correo', models.CharField(db_column='Correo', max_length=200)),
                ('direccion', models.CharField(db_column='Direccion', max_length=50)),
                ('cantidad', models.CharField(db_column='Cantidad', max_length=45)),
                ('estado', models.IntegerField(db_column='Estado')),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id_destino', models.AutoField(db_column='id_Destino', primary_key=True, serialize=False)),
                ('departamento', models.CharField(db_column='Departamento', max_length=50)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=45)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'destino',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id_detalle_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('habitaciones', models.IntegerField()),
                ('adulto', models.IntegerField()),
                ('infante', models.IntegerField()),
                ('comentarios', models.CharField(max_length=500)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospedaje',
            fields=[
                ('idhospedaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=30)),
                ('tipo_hospedaje', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=45)),
                ('tarifa_base', models.FloatField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'hospedaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospedajeAcomodacion',
            fields=[
                ('id_hospedaje_acomodacion', models.AutoField(primary_key=True, serialize=False)),
                ('temporada', models.CharField(max_length=20)),
                ('tarifa_agencia', models.FloatField()),
                ('tarifa', models.FloatField()),
                ('estado_hospeacomo', models.IntegerField()),
            ],
            options={
                'db_table': 'hospedaje_acomodacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fin', models.DateField()),
                ('noche', models.IntegerField()),
                ('incluye', models.CharField(max_length=200)),
                ('no_incluye', models.CharField(max_length=200)),
                ('costo', models.FloatField()),
                ('estado', models.IntegerField()),
                ('disponibilidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'paquete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaqueteTour',
            fields=[
                ('idpaquete_tour', models.AutoField(db_column='idPaquete_tour', primary_key=True, serialize=False)),
                ('condicion', models.IntegerField()),
            ],
            options={
                'db_table': 'paquete_tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idpermiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('estado', models.IntegerField(db_column='Estado')),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('idpermiso_usuario', models.AutoField(db_column='idPermiso_usuario', primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'permiso_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.AutoField(db_column='idReserva', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('fecha_inicio', models.DateField(db_column='Fecha_inicio')),
                ('fecha_fin', models.DateField(db_column='Fecha_fin')),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('total', models.FloatField(db_column='Total')),
                ('estado_reserva', models.CharField(db_column='Estado_reserva', max_length=25)),
                ('metodo_pago', models.CharField(db_column='Metodo_pago', max_length=25)),
                ('estado', models.IntegerField(db_column='Estado')),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tour', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('duracion', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_doc', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=200)),
                ('sexo', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('rol', models.IntegerField()),
                ('login', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
