# Generated by Django 5.0.6 on 2024-08-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_paquetetour_id_hospedaje_acomodacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='telefono',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
